id: fhir.example
canonical: http://example.org
name: mwe
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: Example Publisher
  url: http://example.org/example-publisher
parameters:
  path-resource:
    - input/resources/nested